### ISSUE TITLE
Race condition issue with RouteLocalizationConvention.Apply

### ISSUE THREAD

**Issue by tkallsen** [Dresel/RouteLocalization.AspNetCore#4]
It looks like a class derived from IApplicationModelConvention can be called multiple times by ASP.NET; if two requests comes in at the same time while the application is starting up it seems to be called twice.

This leads to an InvalidOperationException on row 31 in RouteTranslator.cs, which then aborts the startup. When RouteLocalizationConvention.Apply is called again on subsequent requests it will fail with an InvalidOperationException: "Any of ActionModels is completely translated".

It's pretty easy to simulate by adding a Thread.Sleep(5000) to TranslateActionRouteProcessor.cs:52, and while the application is starting in one browser, make another request with a different browser.

As a workaround I have added a lock() in RouteLocalizationConvention.Apply which prevents the the first error, however, if there are any concurrent requests during startup they will still fail with the InvalidOperationException: "Any of ActionModels is completely translated".

Check out https://github.com/tkallsen/RouteLocalization.AspNetCore/commit/1f21984c6a3199620342a2708d19147c8e030dfa

**Comment by Dresel** [comment]
Interesting, didn't know that, thanks for letting us know.

So I guess best bet would be to lock and add an `Initialized` property which skips the routine if already initialized?

**Comment by tkallsen** [comment]
Yeah, sounds like a good idea. However, I must say that this kind of feels like a bug in ASP.NET that it can be called multiple times...

**Comment by Dresel** [comment]
I just tried and couldn't reproduce the race condition, so you might be right with

> However, I must say that this kind of feels like a bug in ASP.NET that it can be called multiple times...

Which version and environment are you using? Can you reproduce this with a simpler sample like described in the [docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-2.2#sample-modifying-the-applicationmodel)?

**Comment by tkallsen** [comment]
> I just tried and couldn't reproduce the race condition

With the Thread.Sleep present? I think when it has happened in production for us it has been when the browser sends a request for the root page and for favicon.ico simultaneously. I can reproduce it consistently if I add Sleep to TranslateActionRouteProcessor and just start the project in Chrome, and while it hangs on the Thread.Sleep, call the same URL with Edge (might work with another tab in Chrome as well).

> Which version and environment are you using? Can you reproduce this with a simpler sample like described in the [docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-2.2#sample-modifying-the-applicationmodel)?

Win10 Chrome/Edge (for this test), VS 2017.

See https://github.com/tkallsen/ApplicationModelConventionTest for a testproject with just a test ApplicationModelConvention. I get several lines written to the Debug-output, so it's called several times as well (if I make a second request with a different browser while the start request hangs on the Thread.Sleep).

**Comment by Dresel** [comment]
Thanks. I have identified the problem.

`RouteTranslatorOptions.RouteTranslatorAction(RouteTranslator)` should not be called within `Apply`.

**Comment by tkallsen** [comment]
Alright, you can disregard my PR then ;)

**Comment by Dresel** [comment]
Nevermind - I hope I'll find some time to push a new NuGet package this evening :)

If you have any other feedback regarding `RouteLocalization.AspNetCore` - I'll really appreciate it.

**Comment by tkallsen** [comment]
It's a very nice library that supports all use cases that we have.

The only other issue that I have had is that you get a warning if you try to filter an async controller-method with .Filter, since I'm not awaiting it.

```
setup.UseCultures(new[] { "en", "sv" })
    .WhereUntranslated()
    .Filter<MiscController>(controller => controller.Index())
    .AddDefaultTranslation();
```

If Index() is async. If you try to await it you get the error "Async lambda expressions cannot be converted to expression trees". Maybe a different overload for Filter could use a string representation of the action instead, like WhereAction.

Very minor issue ;)

**Comment by Dresel** [comment]
Can you test either the development branch or NuGet version [1.0.1-rc1](https://www.nuget.org/packages/RouteLocalization.AspNetCore/1.0.1-rc1)?
